import React, { useState, useEffect } from 'react';
import { Modal } from '../common/Modal';
import { api } from '../../lib/api';
import { formatDate } from '../../lib/utils';
import { Badge } from '../common/Badge';
import { EduSenseLogo } from '../common/EduSenseLogo';
import { Printer, Download, GraduationCap, Calendar, FileText, CheckCircle } from 'lucide-react';

interface StudentReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  studentId: string;
}

export const StudentReportModal: React.FC<StudentReportModalProps> = ({ isOpen, onClose, studentId }) => {
  const [report, setReport] = useState<any>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    if (isOpen && studentId) {
      setIsLoading(true);
      api.getStudentReport(studentId)
        .then((data) => setReport(data))
        .catch(() => setReport(null))
        .finally(() => setIsLoading(false));
    }
  }, [isOpen, studentId]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Official Academic Transcript & Performance Dossier"
      subtitle="Generated by SC EduSense AI Academic Intelligence Platform"
      maxWidth="3xl"
    >
      {isLoading ? (
        <div className="py-12 text-center text-slate-400 animate-pulse">
          Generating verified academic performance dossier...
        </div>
      ) : !report ? (
        <div className="py-8 text-center text-slate-400">
          Unable to generate academic report. No database record found.
        </div>
      ) : (
        <div className="space-y-6 print:m-0">
          {/* Official Document Banner */}
          <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800">
            <EduSenseLogo size="sm" showTagline={true} />
            <div className="flex items-center gap-2 print:hidden">
              <button
                onClick={handlePrint}
                className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white shadow-xs cursor-pointer"
              >
                <Printer className="w-3.5 h-3.5" />
                Print / Save PDF
              </button>
            </div>
          </div>

          {/* Student Header */}
          <div className="bg-slate-50 dark:bg-slate-800/60 p-4 rounded-xl border border-slate-200 dark:border-slate-700 flex flex-wrap items-center justify-between gap-4">
            <div>
              <h2 className="text-base font-bold text-slate-900 dark:text-white">
                {report.student.profile?.full_name}
              </h2>
              <div className="flex flex-wrap items-center gap-3 text-xs text-slate-500 dark:text-slate-400 mt-1">
                <span>Roll: <strong>{report.student.roll_number}</strong></span>
                <span>Major: <strong>{report.student.major}</strong></span>
                <span>Semester: <strong>{report.student.semester}</strong></span>
              </div>
            </div>
            <div className="text-right">
              <div className="text-xs text-slate-500">Overall Academic Standing</div>
              <div className="text-xl font-extrabold text-indigo-600 dark:text-indigo-400">
                {report.analytics?.overall_academic_score || 0}%
              </div>
              <Badge riskLevel={report.analytics?.academic_risk} className="mt-1" />
            </div>
          </div>

          {/* Metrics summary */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3 bg-white dark:bg-slate-800/40 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <div className="text-[11px] text-slate-500 font-medium uppercase">Attendance</div>
              <div className="text-lg font-bold text-slate-900 dark:text-white mt-1">
                {report.analytics?.attendance_percentage || 0}%
              </div>
            </div>
            <div className="p-3 bg-white dark:bg-slate-800/40 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <div className="text-[11px] text-slate-500 font-medium uppercase">Assignment Avg</div>
              <div className="text-lg font-bold text-slate-900 dark:text-white mt-1">
                {report.analytics?.assignment_average || 0}%
              </div>
            </div>
            <div className="p-3 bg-white dark:bg-slate-800/40 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <div className="text-[11px] text-slate-500 font-medium uppercase">Exam Average</div>
              <div className="text-lg font-bold text-slate-900 dark:text-white mt-1">
                {report.analytics?.exam_average || 0}%
              </div>
            </div>
            <div className="p-3 bg-white dark:bg-slate-800/40 rounded-xl border border-slate-200 dark:border-slate-800 text-center">
              <div className="text-[11px] text-slate-500 font-medium uppercase">Enrolled Courses</div>
              <div className="text-lg font-bold text-slate-900 dark:text-white mt-1">
                {report.enrollments?.length || 0}
              </div>
            </div>
          </div>

          {/* Enrolled Courses */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
              Enrolled Courses & Credits
            </h4>
            <div className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden text-xs">
              <table className="w-full text-left">
                <thead className="bg-slate-50 dark:bg-slate-800/60 text-slate-500">
                  <tr>
                    <th className="p-2.5 font-semibold">Course Code</th>
                    <th className="p-2.5 font-semibold">Course Title</th>
                    <th className="p-2.5 font-semibold">Credits</th>
                    <th className="p-2.5 font-semibold">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {report.enrollments?.map((en: any) => (
                    <tr key={en.id}>
                      <td className="p-2.5 font-medium text-slate-900 dark:text-white">{en.course?.code}</td>
                      <td className="p-2.5 text-slate-600 dark:text-slate-300">{en.course?.name}</td>
                      <td className="p-2.5 text-slate-600 dark:text-slate-300">{en.course?.credits}</td>
                      <td className="p-2.5">
                        <span className="text-emerald-600 font-semibold">{en.status}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Exam Results */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
              Examination Performance
            </h4>
            {report.exam_results?.length === 0 ? (
              <p className="text-xs text-slate-400 italic">No formal examination marks recorded.</p>
            ) : (
              <div className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden text-xs">
                <table className="w-full text-left">
                  <thead className="bg-slate-50 dark:bg-slate-800/60 text-slate-500">
                    <tr>
                      <th className="p-2.5 font-semibold">Exam Name</th>
                      <th className="p-2.5 font-semibold">Score</th>
                      <th className="p-2.5 font-semibold">Grade</th>
                      <th className="p-2.5 font-semibold">Evaluation Date</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                    {report.exam_results?.map((res: any) => (
                      <tr key={res.id}>
                        <td className="p-2.5 font-medium text-slate-900 dark:text-white">{res.exam?.name}</td>
                        <td className="p-2.5 text-slate-600 dark:text-slate-300">{res.marks_obtained} / {res.exam?.maximum_marks}</td>
                        <td className="p-2.5">
                          <Badge grade={res.grade} />
                        </td>
                        <td className="p-2.5 text-slate-400">{formatDate(res.graded_at)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Footer note */}
          <div className="pt-4 border-t border-slate-100 dark:border-slate-800 text-[10px] text-slate-400 flex justify-between items-center">
            <span>Generated on: {formatDate(report.generated_at)}</span>
            <span>SC EduSense AI • Cryptographically Signed Record</span>
          </div>
        </div>
      )}
    </Modal>
  );
};
